# Generated by Django 4.2 on 2023-04-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banda_anio_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='anio_creacion',
            field=models.TextField(default='some string', max_length=20),
        ),
        migrations.AlterField(
            model_name='banda',
            name='integrantes',
            field=models.IntegerField(default='some string'),
        ),
    ]
