# Generated by Django 4.2 on 2023-04-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_banda_anio_creacion_alter_banda_integrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='anio_creacion',
            field=models.IntegerField(default='some string'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='integrantes',
            field=models.CharField(default='some string', max_length=50),
        ),
    ]
