# Generated by Django 4.2 on 2023-04-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_banda_integrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='descripcion',
            field=models.TextField(max_length=1500),
        ),
    ]
